# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WebService-TestSystem
version:      0.06
version_from: lib/WebService/TestSystem.pm
installdirs:  site
requires:
    Carp:                          0
    Config::Simple:                0
    Getopt::Long:                  0
    Pod::Usage:                    0
    SOAP::Lite:                    0
    WebService::TicketAuth:        1.04
    XML::Parser:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
