#!/usr/bin/perl -w

use SOAP::Transport::HTTP;

use WebService::TestSystem;

# don't want to die on 'Broken pipe' or Ctrl-C
$SIG{PIPE} = $SIG{INT} = 'IGNORE';

my $daemon = SOAP::Transport::HTTP::Daemon
    -> new (LocalPort => 8081, Reuse => 1 )
    -> dispatch_to('WebService::TestSystem')
    -> options({compress_threshold => 10000})
    ;

print "Contact to SOAP server at ", $daemon->url, "\n";
$daemon->handle;
